openstack-k8s-operators/infra-operator

apis/go.mod
apis/go.sum
controllers/client/openstackclient_controller.go
controllers/memcached/memcached_controller.go
controllers/rabbitmq/transporturl_controller.go
go.mod
go.sum

instead of int. This allows us to use more fine grained timeout value such as 0.1, and encodes the unit in the type itself.
Depends-On: https://github.com/openstack-k8s-operators/lib-common/pull/155

Use time.Duration for timeout

---

.github/workflows/build-openstack-operator.yaml

We build containers and push to registry in post merge workflow. Not building container for each hash can cause issue becuase of missing container tags. Pin-custom-bundle-dockerfile.sh (openstack-operator) can pin to hash for which images are not available.

Drop paths-ignore from build operator workflow

---

.ci-operator.yaml

ci-operator is the tool that handles the process of building images and running workflows in Prow jobs. By adding this configuration in the repo, we can replace the base root image (which will serve as base for most of the jobs) along with code changes, when upgrading dependencies (golang for instance)
This file has no effect for now, only after updating ci-operator config on openshift/release, in another PR.

Adds ci-operator.yaml

---

controllers/memcached/memcached_controller.go
pkg/memcached/statefulset.go

When we create a Memcached CR instance for individual services, then we should ideally append -memcached to the name of the configmap to avoid conflicing with the service configmaps. This change appends the -memcached to the configmap name accordingly.

Change name of memcached configmap

---

Makefile
apis/memcached/v1beta1/memcached_types.go

Having a CRD field with omitempty tag with a kubebuilder default value defined can cause unexpected behavior. See
https://github.com/gibizer/operator-lint/blob/main/linters/crd/C003 for details.
So this patch remove the problematic definitions and bumps the operator-lint version to 0.3.0 that has a check to cover this.

Fix omitempty + default value

---

.github/workflows/build-infra-operator.yaml
.github/workflows/golangci-lint.yaml

Now this operator is developed with golang 1.19 instead of 1.18, so we should use the correct version.

Use golang 1.19 in CI

---

Makefile
config/default/manager_default_images.yaml
config/samples/client_v1beta1_openstackclient.yaml

We imported container build tools from TripleO as TCIB[1]. Now we are retiring TripleO and should complete the migration.
[1] https://github.com/openstack-k8s-operators/tcib

Replace TripleO images by TCIB images

---

config/default/manager_default_images.yaml
config/samples/client_v1beta1_openstackclient.yaml

This fixes a typo (missing -) in the default image names, which were introduced by a733e908da2d1415ba7de9ac19ab39d883f83c03.

Fix wrong image names

---

pkg/memcached/statefulset.go

... to avoid name collision with the other operators. This also allows us to name pods deployed by the statefulset with memcached- prefix, which helps identifying for which service the pod is deployed.

memcached: Add memcached- prefix to stateful set name

---

apis/bases/memcached.openstack.org_memcacheds.yaml
apis/memcached/v1beta1/memcached_types.go
config/crd/bases/memcached.openstack.org_memcacheds.yaml
controllers/memcached/memcached_controller.go

This adds ReadyCount field in status, so that users can understand number of pods properly deployed. This field is supported by most of CRs and adding this to Memcached CR makes the interface more consistent across all CRs.

Memcached: Present number of pods in status

---

pkg/memcached/service.go
pkg/memcached/statefulset.go

We have to use different labels for different CR instance because we deploy one service resource per CR instance.

Fix app label for memcached resources

---

config/manifests/bases/infra-operator.clusterserviceversion.yaml

This should hide the infra operator package/bundle in the OpenShift console as we only want the main OpenStack operator to show up there.

CSV: Set operator-type: non-standalone

---

controllers/memcached/memcached_controller.go
pkg/memcached/service.go
pkg/memcached/statefulset.go

Pod DNS is supposed to look like `<stateful set name>-<index>.<service name>`
This fixes the wrong hostname format used to generate server list status fields.
This also removes redundant `memcached` from resource names. Now individual operators are supposed add it as CR name suffix, thus adding it again in memcached controller causes redundant names.

Fix hostname in server list fields

---

config/samples/network_v1beta1_netconfig.yaml

Use the same vlan ids we configure with nncp and use in edpm nodes.

Match vlan ids

---

apis/bases/network.openstack.org_ipsets.yaml
apis/bases/network.openstack.org_netconfigs.yaml
apis/go.mod
apis/go.sum
apis/network/v1beta1/common_webhook.go
apis/network/v1beta1/ipset_types.go
apis/network/v1beta1/ipset_webhook.go
apis/network/v1beta1/ipset_webhook_test.go
apis/network/v1beta1/netconfig_types.go
apis/network/v1beta1/netconfig_webhook.go
apis/network/v1beta1/netconfig_webhook_test.go
config/crd/bases/network.openstack.org_ipsets.yaml
config/crd/bases/network.openstack.org_netconfigs.yaml
config/webhook/manifests.yaml
test/functional/base_test.go
test/functional/ipset_controller_test.go
test/functional/netconfig_webhook_test.go

**A)** Adds further validations for IPSet and NetConfig.
NetConfig:
IPSet:
* Create
- Validates that there is a NetConfig in the namespace
* Create and Update
- networks are uniq in the list
- networks and subnets exist in netcfg
- FixedIP is a valid IP address
- FixedIP has correct IP version of subnet
- FixedIP is in the subnet cidr
- Route is only specified on a single network
* Update
- if a previous requested network is still in the list
- if subnet changed within a network
- if fixedIP changed
- if defaultRoute changed
NetConfig:
* Create
- validates if there is already a NetConfig in the namespace
* Update
**Note**: those checks will be skipped if there are no IPSets in the namespace. in that case it is save to customize the NetConfig as needed.
- validate if a network was removed …

[IPAM] extend IPSet and NetConfig validation and adds Immutable feature

---

apis/network/v1beta1/ipset_webhook.go
test/functional/ipset_controller_test.go

This changes the webhook to not block updated Spec.Immutable to allow requesting a new network.
Jira: [OSP-19996](https://issues.redhat.com//browse/OSP-19996)

[IPAM] Allow flipping Spec.Immutable parameter

---

zuul.d/jobs.yaml
zuul.d/projects.yaml

Now dataplane uses infra-operator for IPAM stuff. Let's avoid breaking the EDPM deployment with changes here.
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/328

Add edpm jobs to infra-operator

---

.github/workflows/build-infra-operator.yaml

The image name/repo name for infra operator doesn't have openstack in its name. Removing openstack name so that we can sort github status list correctly [1].
[1] https://github.com/gibizer/openstack-k8s-status/tree/main

Remove openstack from workflow name

---

Makefile

This reverts commit 75a00cd30a5238afbe9171aa1bbc2e654e1bb482.
Reason for revert:
https://github.com/openshift/release/pull/41180 was merged which resolves the permission problem in CI. Thus we can revert the change and use the consistent command.

Revert "[Makefile] Fix cp -a permission issue in make manifests"

---

controllers/client/openstackclient_controller.go
controllers/memcached/memcached_controller.go
controllers/network/dnsmasq_controller.go
controllers/redis/redis_controller.go

This ensures the controller watches service account, role, and role bindings to reconcile these resources in case any change is made.

Watch RBAC resources to trigger reconcile

---

.github/workflows/lints.yaml

To catch unwanted local go.mod replace lines to be merged this patch adds a check for it.

Add a github action that checks for go.mod replace

---

tests/functional/dnsmasq_controller_test.go

This function is subset of GetConfigMap and can be replaced.

Replace AssertConfigMapExists

---

controllers/network/ipset_controller.go

os-net-config used networkconfig templates expect default route appended to other ctlplane static routes.

Append default route in routes

---

config/samples/network_v1beta1_netconfig.yaml

Since `config/samples/network_v1beta1_netconfig.yaml` is used in `install_yamls` for NetConfig setup, when we try to spawn multiple instances a couple of them try to use addresses that are already used elsewhere and that led `os-net-config` to fail (and left the network configuration broken) E.g.
```
[root@edpm-compute-6 ~]# grep ERR /var/log/os-net-config.log 
2023-07-19 06:11:07.797 ERROR os_net_config.impl_ifcfg.apply Failure(s) occurred when applying configuration
2023-07-19 06:11:07.797 ERROR os_net_config.impl_ifcfg.apply stdout: ERROR     : [/etc/sysconfig/network-scripts/ifup-eth] Error, some other host (46:2F:73:15:5F:29) already uses address 172.17.0.30.
2023-07-19 06:11:07.797 ERROR os_net_config.impl_ifcfg.apply stdout: ERROR     : [/etc/sysconfig/network-scripts/ifup-eth] …
```

Modified internal subnets allocation range in `network_v1beta1_netconfig.yaml`

---

config/samples/rabbitmq_v1beta1_transporturl.yaml
kuttl-test.yaml
tests/kuttl/tests/memcached/01-assert.yaml
tests/kuttl/tests/memcached/01-deploy-memcached.yaml
tests/kuttl/tests/memcached/05-cleanup-memcached.yaml
tests/kuttl/tests/memcached/05-errors.yaml
tests/kuttl/tests/rabbitmq/01-assert.yaml
tests/kuttl/tests/rabbitmq/01-deploy-transporturl.yaml
tests/kuttl/tests/rabbitmq/05-cleanup-transporturl.yaml
tests/kuttl/tests/rabbitmq/05-errors.yaml

This updates the kuttl tests so that we can test `Memcached` CR and `TransportURL` CR.

Add more kuttl tests coverage

---

zuul.d/jobs.yaml

We don't have to run zuul jobs when the change affects only kuttl tests or env tests.

Stop executing zuul jobs in test code change

---

config/manifests/bases/infra-operator.clusterserviceversion.yaml

The existing link is invalid. Also maturity was not consistent with API version(v1beta) currently presented by this operator.

Fix link and maturity in csv

---

apis/bases/network.openstack.org_dnsmasqs.yaml
apis/network/v1beta1/dnsmasq_types.go
config/crd/bases/network.openstack.org_dnsmasqs.yaml
controllers/network/dnsmasq_controller.go

This option allows to not cache the NXDOMAIN nor any other negative answer from the forwarders.
This is especially interesting when a DNS query happens when an operator endpoint isn't 100% ready, meaning its DNS record isn't known from the internal openshift-dns services.
Without that option, the dnsmasq service will cache the NXDOMAIN for the default TTL duration, meaning it will serve the cached answer instead of checking back.

Allow no-negcache option in dnsmasq

---

tests/functional/base_test.go
tests/functional/dnsmasq_controller_test.go

Following #114, we need to ensure the formatting is correct for option without any value such as the new no-negcache one we added.

Add missing tests for no-negcache option

---

.ci-operator.yaml
.github/create_bundle.sh
.github/workflows/build-infra-operator.yaml
.prow_ci.env
apis/memcached/v1beta1/memcached_types.go
apis/network/v1beta1/dnsmasq_types.go
apis/redis/v1beta1/redis_types.go
config/default/manager_default_images.yaml
config/manifests/bases/infra-operator.clusterserviceversion.yaml
tests/kuttl/tests/memcached/01-assert.yaml

This PR adds support for installing the operator in disconnected network environments. To build with image-digests set USE_IMAGE_DIGESTS=true before running make bundle.
For Prow jobs we are enabling this via .prow-ci.env
This drops the old logic from create_bundle.sh which has been broken with operator-sdk's make bundle for some time.
(NOTE: this currently requires a secure registry)

Support disconnected network environments

---

apis/bases/network.openstack.org_netconfigs.yaml
apis/network/v1beta1/netconfig_types.go
config/crd/bases/network.openstack.org_netconfigs.yaml

The description for networks and subnet uses the "triple network" and "tripleo subnet" wording. Drop "tripleo", it as it is not relevant.

Remove "tripleo" from Network/Subnet description

---

apis/bases/network.openstack.org_dnsmasqs.yaml
apis/network/v1beta1/dnsmasq_types.go
config/crd/bases/network.openstack.org_dnsmasqs.yaml
config/samples/network_v1beta1_dnsmasq.yaml

Allow setting local domains and not always forward queries to upstream servers.

Allow setting local domains

---

apis/network/v1beta1/ipset_webhook_test.go
apis/network/v1beta1/netconfig_webhook_test.go
tests/functional/ipset_controller_test.go

Ths pointer library[1] has been deprecated and replaced by ptr. This change refactors the usage on the new library[2] and usage.
[1] https://pkg.go.dev/k8s.io/utils/pointer
[2] https://pkg.go.dev/k8s.io/utils/ptr

Refactor use of pointer library

---

config/manifests/bases/infra-operator.clusterserviceversion.yaml

Update to use new 'features.operators.openshift.io' annotations format for disconnected support
Jira: [OSP-30201](https://issues.redhat.com//browse/OSP-30201)

required infra annotations for OCP 4.14+

---

PROJECT
config/samples/kustomization.yaml
config/samples/network_v1beta1_reservation.yaml

This PR fixes some bundle validations:
WARN[0000] Skipping definitions parsing for API {}: Go type not found
WARN[0000] Warning: Value network.openstack.org/v1beta1, Kind=Reservation: provided API should have an example annotation
Adds a sample for the Reservation CR. Even though this is only used internally it won't hurt to add it.
Additionally, removes the 'service' definition from PROJECT as it only has a controller.

Fix bundle validations (add sample reservation)

---

controllers/memcached/memcached_controller.go
controllers/network/dnsdata_controller.go
controllers/network/dnsmasq_controller.go
controllers/network/ipset_controller.go
controllers/network/service_controller.go
controllers/rabbitmq/transporturl_controller.go
controllers/redis/redis_controller.go
main.go
tests/functional/suite_test.go

This automatically adds additional fields like reconcile_id etc.. from the controller context.
before :
`2023-05-18T01:53:14+03:00 INFO  controllers.KeystoneAPI Reconciled Service init successfully`
after:
`2023-10-19T08:57:36+03:00       INFO    Controllers.memcached   StatefulSet memcached - updated {"controller": "memcached", "controllerGroup": "memcached.openstack.org", "controllerKind": "Memcached", "Memcached": {"name":"memcached","namespace":"openstack"}, "namespace": "openstack", "name": "memcached", "reconcileID": "9e359c97-7fd5-4d16-9fb6-fcccc395779a"}
`
*by using per reconcile function respective logger objects, the intention is to lay the ground for parallel reconciliation in future and avoid race conditions as ctx objects are reconcile run specific.

switch to structured logging

---

Makefile

specify version for operator-sdk for make bundle
download operator-sdk pinned version when generating bundle update make bundle to use local operator-sdk
update to 1.31 version

operator-sdk local bin

---

apis/network/v1beta1/ipset_webhook.go
apis/network/v1beta1/netconfig_types.go
config/samples/network_v1beta1_netconfig.yaml
controllers/network/ipset_controller.go
tests/functional/base_test.go

This could be a temporary change to make dataplane networks small case and align with what we use in
control plane network attachments etc or permanent if we want to make networks/subnets case in-sensitive.

Make the network names case insensitive

---

controllers/network/ipset_controller.go

Otherwise networks in reservations does not match that of NetConfig and hence reservations don't work if there are more than one node.

Create reservations using the networks in NetConfig

---

.prow_ci.env
Dockerfile
Makefile
config/manifests/bases/infra-operator.clusterserviceversion.yaml

This change ensures the infra-operator is built with FIPS compliance.

This change adds requirements for FIPS

---

controllers/network/dnsmasq_controller.go

When the namespace is deleted ServiceAccount creation will fail and because that runs before checking if the DNSMasq is being deleted too the DNSMasq will never be deleted. This patch moves the check before the SA creation.
Fixes: [OSP-27793](https://issues.redhat.com//browse/OSP-27793)

[DNSMasq]Check delete before creating ServiceAccount

---

apis/bases/memcached.openstack.org_memcacheds.yaml
apis/memcached/v1beta1/memcached_funcs.go
apis/memcached/v1beta1/memcached_types.go
config/crd/bases/memcached.openstack.org_memcacheds.yaml
controllers/memcached/memcached_controller.go
tests/kuttl/tests/memcached/01-assert.yaml

Adds a TLSSupport to the memcached status which reflects if the instance got configured with TLS. Same flag was also introduced to mariadbdatabase a while back.
Also
* adds functions to return the memcached server list and the status of tls support, which can be used for clients for easy consumption. They could be used as an intermediate step for https://github.com/openstack-k8s-operators/infra-operator/pull/190
* creates the service list for memcached fqdn svc hostnames to be able to use fqdn hostnames in tls certs.
Jira: [OSPRH-5283](https://issues.redhat.com//browse/OSPRH-5283)

[tlse] add TLS status config, func to return server list and tls support

---

apis/network/v1beta1/netconfig_webhook.go

Some of the conditionals were needlessly checking for nil value in cases already covered by previous checks.

Simplification of webhook conditionals

---

apis/memcached/v1beta1/memcached_funcs.go
apis/test/helpers/memcached.go

For tls, in https://github.com/openstack-k8s-operators/infra-operator/pull/192 changed the server lists to contain the svc fqdn, but missed to update the test helpers.

[memcached] add funcs to return quoted serverList and update test helpers

---

apis/network/v1beta1/common_webhook.go
apis/network/v1beta1/ipset_webhook.go
apis/network/v1beta1/ipset_webhook_test.go

This allows to only request the default gw for a network if it is configured on the referenced subnet.
Closes: https://github.com/openstack-k8s-operators/infra-operator/issues/200

[ipset] add validation in ipset webhook for default gw to be configured

---

Makefile

Change[0] in controller-runtime is causing our tests to fail with go version mismatch.
This version restriction should be removed once the issue is fixed in the controller-runtime
[0] https://github.com/kubernetes-sigs/controller-runtime/pull/2693

Pin setup-envtest to last working commit

---

config/manifests/bases/infra-operator.clusterserviceversion.yaml

recent changes didn't update the CSV yaml file.
This updates to match what make bundle modifies things with

update CSV with tls

---

controllers/rabbitmq/transporturl_controller.go

The transporturl  controller did a separate client.Update after
it initialized it status then continued the normal reconciliation. As it
is explicitly updated the status subresource and no finalizer is added
this probably works. However to allow easier reasoning about when the
instance is updated this patch removes the explicit Update call and
instead returns immediately to use the deferred PatchInstance call
as the only place that persists the instance.

TransportURL: rely on PatchInstance instead of manual Update

---

.gitignore
controllers/network/ipset_controller.go
tests/functional/base_test.go
tests/functional/ipset_controller_test.go

This change ensure that the ipset network order
is preserved in the status.reservation
This is requried to ensure the dns search domain order
is defined by the order of the network list.
Closes: [OSPRH-6672](https://issues.redhat.com//browse/OSPRH-6672)

ensure network order is preserved

---

apis/test/helpers/memcached.go
apis/test/helpers/transport.go

This updates the test helpers for memcached and transport URL to set ObservedGeneration

Set ObservedGeneration in test helpers

---

config/manifests/bases/infra-operator.clusterserviceversion.yaml

Also removes deprecated operators.openshift.io/infrastructure-features annotation.
Jira: https://issues.redhat.com/browse/OSPRH-7941

Add required infrastructure annotations

---

templates/memcached/config/memcached

Adjust the handling of the `$POD_IPS` variable to allow for multiple pod IPs. This change takes the comma separated list of PodIPs and replaces the comma with a space to make it work with the rest of the statement for building the listen IPs.
Implements #233

memcached: replace ',' in $POD_IPS by space

---

apis/bases/memcached.openstack.org_memcacheds.yaml
apis/memcached/v1beta1/memcached_types.go
apis/memcached/v1beta1/zz_generated.deepcopy.go
config/crd/bases/memcached.openstack.org_memcacheds.yaml
pkg/memcached/service.go
pkg/memcached/statefulset.go

Related: https://issues.redhat.com/browse/OSPRH-9295

Add AntiAffinity and NodeSelector capabilities to memcached

---

apis/redis/v1beta1/redis_types.go
apis/redis/v1beta1/redis_webhook.go

This commit adds a CrMaxLengthCorrection parameter to the redis resource so it doesn't exceed the limit.

Add CrMaxLengthCorrection to Redis

---

.gitignore
apis/bases/network.openstack.org_ipsets.yaml
apis/bases/network.openstack.org_netconfigs.yaml
apis/network/v1beta1/ipset_types.go
apis/network/v1beta1/netconfig_types.go
apis/network/v1beta1/netconfig_webhook.go
config/crd/bases/network.openstack.org_ipsets.yaml
config/crd/bases/network.openstack.org_netconfigs.yaml
config/manifests/bases/infra-operator.clusterserviceversion.yaml
controllers/network/ipset_controller.go
tests/functional/base_test.go
tests/functional/ipset_controller_test.go

This would allow us to identify the ctlplane network when
using custom network and also generate inventory using
the ServiceNetwork.
Jira: https://issues.redhat.com/browse/OSPRH-10125

Add ServiceNetwork attribute to networks in netconfig

---

templates/instanceha/bin/instanceha.py
templates/instanceha/config/config.yaml

This commit fixes a couple of issues:
1. Catch case where all the faulty computes are dumping
In case all the stale_computes are kdumping we want to make sure
the check_kdump function returns an empty list, otherwise they may
be evacuated without waiting the dump to be collected.
2. Wrap reverse dns lookup in try/except block
If DNS is broken calling socket.gethostbyaddr() could result in
an unexpected pod crash.
Let's wrap the call in try/except with the expectation that a
reverse dns lookup failure should not prevent evacuation,
worst case scenario we would not capture the memory dump and
the user will have a "ERROR Could not perform reverse dns lookup for: X"
in the logs hinting at resolution not working.
It also introduces two new config options:
TAGGED_IMAGES (default=true) …

Enable toggling tagged flavors/images and small fixes

---

controllers/instanceha/instanceha_controller.go
controllers/memcached/memcached_controller.go
controllers/rabbitmq/transporturl_controller.go
controllers/redis/redis_controller.go

It is hidden right now if there is an error in configured named fields and index. Lets log the error and return the current state of requests.
With this the findObjectsForSrc() will exit with an hidden error like:
```
"error": "Index with name field:.spec.ksmTls.caBundleSecretName does not exist"
```

Make sure to log error in findObjectsForSrc()

---

templates/instanceha/bin/instanceha.py

This commit adds one more way of fencing a compute node, using baremetal apis (metal3).
It works by adding a reboot annotation, see:
https://book.metal3.io/bmo/reboot_annotation.html
{"annotations":{"reboot.metal3.io/iha":"{\"mode\": \"hard\"}"}}
After the evacuation is completed this annotation is removed and the compute host powered back on.
fencing.yaml should contain something like:
```
FencingConfig:
edpm-compute-1:
agent: bmh
token: <long-token>
host: edpm-compute-1
namespace: openstack
```
The token is obtained with something like the following:
```
kubectl create serviceaccount k8sadmin -n kube-system 
kubectl create clusterrolebinding k8sadmin --clusterrole=cluster-admin --serviceaccount=kube-system:k8sadmin 
kubectl -n kube-system describe secret $(sudo kubectl -n kube-system …
```

Add BaremetalHost annotation-based fencing

---

templates/instanceha/bin/instanceha.py
templates/instanceha/config/config.yaml

This commit increases the default value of 'POLL' from 30s to 45s. 
The reason is that the check_kdump functionality has an internal hard-coded timeout of 30s and this may induce race conditions if POLL is set to the same value.
A warning has been added to make sure users are notified if POLL=30s.
Finally, we take the chance to normalize the retcode for bmh_fencing.

Increase POLL interval to avoid race with check_kdump

---

pkg/instanceha/funcs.go
templates/instanceha/bin/instanceha.py

This commit adds a liveness probe to the InstanceHa pod so to eventually recover from the pod not responding.
Since this could interrupt the recovery workflow we also add a way to resume evacuations if a host has been previously been disabled and marked by InstanceHa (see "Disabled Reason" in nova).
Jira: https://issues.redhat.com/browse/OSPRH-10412

Add liveness probe and allow InstanceHa to resume evacuations

---

config/manifests/bases/infra-operator.clusterserviceversion.yaml

Spotted a place where I missed a 'HA' vs "Ha', result is that make bundle would generate a duplicate definition in config/manifests/bases/infra-operator.clusterserviceversion.yaml without this patch.

Fix typo / make bundle issue

---

templates/instanceha/bin/instanceha.py
templates/instanceha/config/config.yaml

We've seen issues in the past with nfs servers that would not release locks fast enough for evacuation to complete (see https://bugzilla.redhat.com/show_bug.cgi?id=1755760 for example). 
This commit adds a DELAY parameter so we can wait for a certain amount of time before starting the evacuation.

Add delay parameter

---

apis/bases/network.openstack.org_ipsets.yaml
apis/network/v1beta1/ipset_types.go
config/crd/bases/network.openstack.org_ipsets.yaml

jira: https://issues.redhat.com/browse/OSPRH-11679

Make ServiceNetwork optional in IPSetReservration

---

pkg/redis/statefulset.go

Openshift coreDNS creates the domain name using an string located in dnses.operator.openshift.io. This string can change in the future, calling lib-common/GetDNSClusterDomain the responsability of gathering this information correctly only falls under lib-common intead of all operators.
Resolves: [OSPRH-3627](https://issues.redhat.com//browse/OSPRH-3627)
Depends-on: openstack-k8s-operators/lib-common#580

Use dns cluster info from lib common get function

---

controllers/network/dnsmasq_controller.go

When edpm nodes use the dnsmasq we deploy in OCP they will not be able to get large DNS responses.
DNS messages are restricted to 512 octets, and tools such as dig will try detect that the response has been truncated and then use TCP mode instead.
We can see this happen if we run inside the edpm node the following:
```
$ dig cisco.com TXT
;; Truncated, retrying in TCP mode.
```
With this patch we make the dns OCP service expose the TCP port so the alternative TCP mechanism can be used.

DNS: Support large DNS payloads

---

apis/bases/instanceha.openstack.org_instancehas.yaml
apis/instanceha/v1beta1/instanceha_types.go
config/crd/bases/instanceha.openstack.org_instancehas.yaml
config/default/manager_default_images.yaml
config/manifests/bases/infra-operator.clusterserviceversion.yaml

Hard coding the containerImage value is problematic b/c our build system would not override the value set in the crd automatically, so the variable ends up being set to the wrong image in the crd definition.
Let's try using RELATED_* vars (set by the infra-operator itself, because we can't have two vars using the same value, see https://github.com/openstack-k8s-operators/openstack-operator/pull/1150).
Jira: [OSPRH-13093](https://issues.redhat.com//browse/OSPRH-13093)

Drop the default containerImage parameter and use VAR

---

pkg/redis/statefulset.go

```
[zuul@controller-0 ~]$ oc get redis redis -o yaml                
apiVersion: redis.openstack.org/v1beta1
kind: Redis
metadata:                  
annotations:                                       
kubectl.kubernetes.io/last-applied-configuration: |                                                                                                                                                                                                                                                                                         
{"apiVersion":"redis.openstack.org/v1beta1","kind":"Redis","metadata":{"annotations":{},"name":"redis","namespace":"openstack"},"spec":{"nodeSelector":{"foo":"bar"},"replicas":1}
creationTimestamp: "2024-10-25T06:29:51Z"
generation: 1                
name: redis …
```

Add Affinity to Redis

---

templates/instanceha/bin/instanceha.py

This commit brings the following changes:
1. When evacuations fail we want to update the disable_log_reason field so users can immediately see the reason, plus we can filter out these computes and not try to evacuate them again.
2. We now filter out evacuations that are 'failed' when deciding if a compute can be re-enabled after it has been fenced, as it is preferable to avoid users the additional burden of manually re-enabling the hypervisors if not necessary.
If necessary the LEAVE_DISABLED option can be used to keep a host down.
3. We wrap the initial call to nova api in try/except to give users evidence in the logs if nova is not available.
4. We added a FORCE_ENABLE parameter. If true, ignore any failed evacuation and enable computes after evacuation.
Jira: …

Update disable_reason when evacuation fails and other fixes

---

apis/bases/instanceha.openstack.org_instancehas.yaml
apis/instanceha/v1beta1/instanceha_types.go
config/crd/bases/instanceha.openstack.org_instancehas.yaml

With 502a989f7bbe8291e86750ce1d055feb43f22585 we removed the default value for ContainerImage but forgot to make the parameter optional. 
This commit rectifies this, so users can rely on the defaults set by the operator/webhook.

Make InstanceHA ContainerImage optional

---

apis/topology/v1beta1/topology_types.go

This patch introduces a unified topology validation function that service operators can use to validate `TopologyRef` definitions in their `CRs`.
Key improvements:
- It creates a single entry point (that can be extended as needed) for all topology validation logic
- It accepts a `TopoRef` parameter and handles `nil` checks internally
- It validates `namespace` correctly without requiring `basePath` centralization (that lives in the service API definition)
- Fixes a bug in `ValidateTopologyNamespace` where a `topology` key was erroneously referenced (there's no topology entry in the CRD).
The new validation function provides a base that can be extended for more complex validation requirements in the future while maintaining consistent behavior across all service operators.
Jira: …

Add centralized topology validation function for service operators

---

apis/topology/v1beta1/topology_types.go

This patch fixes how we dereference `topologyRef.namespace`. This is a struct and should have `.Child` to access the fields, and not `.Key` which suggests we're accessing an index of a map.
Jira: https://issues.redhat.com/browse/OSPRH-14626

Fix topology namespace dereference

---

apis/instanceha/v1beta1/instanceha_types.go
apis/instanceha/v1beta1/instanceha_webhook.go
apis/memcached/v1beta1/memcached_types.go
apis/memcached/v1beta1/memcached_webhook.go
apis/network/v1beta1/dnsmasq_types.go
apis/network/v1beta1/dnsmasq_webhook.go
apis/rabbitmq/v1beta1/rabbitmq_types.go
apis/rabbitmq/v1beta1/rabbitmq_webhook.go
apis/redis/v1beta1/redis_types.go
apis/redis/v1beta1/redis_webhook.go
go.mod
tests/functional/memcached_controller_test.go

This patch is a follow up of [1] in the validation `webhook` area. It enhances the validation workflow and it aims to complete the pattern by distributing the `ValidateTopology` logic across the `API` instances.
It is based on [2] and the key improvements include:
- `Distributed validation`: it provides a `ValidateTopology` function across all API instances, ensuring consistent validation throughout the system
- `Optimized validation calls`: it refines how validation is triggered and reduce code duplication; it still requires a basic struct refactor to fully de-duplicate the existing functions, but it can be done as part of a follow up
This patch leverages the centralized topology validator introduced in `infra-operator` [3].
Jira: https://issues.redhat.com/browse/OSPRH-14626
[1] …

Complete webhook validation for topology references

---

tests/functional/base_test.go
tests/functional/dnsmasq_controller_test.go
tests/functional/memcached_controller_test.go

This patch improves our topology testing with several enhancements and extends the `topologyRef` tests:
- `finalizer` verification for each sub component that references a topology
- Updated `Topologies` to support `component-specific` label selectors
This work completes the topology validation improvements initiated in [1], addressing the remaining open points.
Jira: https://issues.redhat.com/browse/OSPRH-15220
[1] nova-operator#941

Improve topology testing coverage

---

pkg/memcached/const.go
pkg/memcached/statefulset.go

This patch represents an improvement of the existing code to make sure we run memcached services using the memcached user (provided by kolla) instead of root.
Jira: https://issues.redhat.com/browse/OSPRH-15334

Run memcached service using memcached user

---

templates/instanceha/bin/instanceha.py
templates/instanceha/config/config.yaml

This commit:
1 Adds a new parameter called TAGGED_AGGREGATES (false by default): this allows operators to enable instanceha only on aggregates marked with the EVACUABLE_TAG metadata, and also to disable/enable this functionality without having to update aggregates.
2 Cleans up a few pieces of code and adds a more explicit and informative warning message if a non-tagged compute has failed.
3 Improves how the reserved_hosts are used. Now we try to enable a compute from the same aggregate of the failed compute (if TAGGED_AGGREGATES are used) or a compute from the same AZ.
4 Fixes a potential issue if fencing is not working, preventing evacuation.

Add TAGGED_AGGREGATES parameter and cleanups

---

apis/memcached/v1beta1/memcached_types.go
apis/network/v1beta1/dnsmasq_types.go
apis/rabbitmq/v1beta1/rabbitmq_types.go
apis/test/helpers/topology.go
apis/topology/v1beta1/topology_types.go
controllers/memcached/memcached_controller.go
controllers/network/dnsmasq_controller.go
controllers/rabbitmq/rabbitmq_controller.go

As a follow up of [1] it is ok to simplify the service operators and blindly pass `instance.Status.LastAppliedTopology` to `EnsureServiceTopology` function provided by infra-operator.
The logic that removes the `finalizer` from an existing `TopologyRef` (only when `LastAppliedTopology != nil`) is now moved here, resulting in a simplification of the current operators logic.
This patch resolves yet another tech debt generated by the fact that we started with a different implementation of `LastAppliedTopology` (based on the `.Name` `string`), that later has been aligned with the existing `TopoRef` struct.
Jira: https://issues.redhat.com/browse/OSPRH-15072
[1] https://github.com/openstack-k8s-operators/placement-operator/pull/285#discussion_r1967176124

Optimize EnsureDeletedTopologyRef condition

---

templates/instanceha/bin/instanceha.py

This commit:
1. Removes a duplicate call to `_host_fence()` in the `process_service` function. The function was being called once without using the return value, and immediately after with error handling.
Co-authored-by: Luca Miccini <lmiccini@redhat.com>

Remove redundant _host_fence() call before result check

---

apis/test/helpers/memcached.go

This change adds a GetDefaultMemcachedSpec test helper which returns memcachedv1.MemcachedSpec. This reduces code duplication and can be used in test helpers of other openstack operators.

Add GetDefaultMemcachedSpec test helper

---

Makefile
tests/functional/bgpconfiguration_controller_test.go

Adds bgp pkg to run functional tests with `make test`. Also adds an envtest to validate when BGPConfiguration CR is deleted, finalizer logic removes owned FRRConfiguration objects.

[bgp] fix Makefile test target + add envtest test case

---

apis/bases/network.openstack.org_bgpconfigurations.yaml
apis/network/v1beta1/bgpconfiguration_types.go
config/crd/bases/network.openstack.org_bgpconfigurations.yaml

Update the JSON tag from 'frrConfigurationNamespace' to 'nodeName' so it matches the field and avoids CRD decoding errors.
Jira: https://issues.redhat.com/browse/OSPRH-16550

[bgp] Mismatch between field name and JSON tag for NodeName.

---

controllers/instanceha/instanceha_controller.go
controllers/memcached/memcached_controller.go
controllers/network/bgpconfiguration_controller.go
controllers/network/dnsdata_controller.go
controllers/network/dnsmasq_controller.go
controllers/network/ipset_controller.go
controllers/rabbitmq/rabbitmq_controller.go
controllers/rabbitmq/transporturl_controller.go
controllers/redis/redis_controller.go

Currently we use deferred call to always update the status field when Reconcile call exits, which seems correct for any other error except when Reconciler exits due to panic.
This change adds a call to recover function and try to handle panic and log error.
Closes: [OSPRH-16967](https://issues.redhat.com//browse/OSPRH-16967)

Do not update status when reconciler exits due to panic

---

controllers/rabbitmq/transporturl_controller.go

The rabbitmq/transporturl_controller implements two method 'GetLog' and 'GetLogger' for getting logger object and are duplicate methods.
This change removes 'GetLog' function as it is not used anywhere.

Remove duplicate func GetLog

---

controllers/instanceha/instanceha_controller.go
controllers/memcached/memcached_controller.go
controllers/network/dnsmasq_controller.go
controllers/rabbitmq/rabbitmq_controller.go
controllers/rabbitmq/transporturl_controller.go
controllers/redis/redis_controller.go

This change uses GetLogger instead of direct use of log.FromContext to support structured logging.

Use structured logging

---

apis/rabbitmq/v1beta1/rabbitmq_types.go

This is a pre-step to upgrade to controller-tools. When updating to controller-tools v0.18.0 the required tag results getting an empty string added to the required list:
```
type: object
required:
+            - ""
- containerImage
type: object
status:
```
Lets remove the tag as it should not be needed when inline the RabbitmqClusterSpecCore.
Related: [OSPRH-12935](https://issues.redhat.com//browse/OSPRH-12935)

Remove required on inline RabbitmqClusterSpecCore

---

apis/network/v1beta1/ipset_webhook.go
apis/network/v1beta1/ipset_webhook_test.go
controllers/network/ipset_controller.go
pkg/ipam/funcs.go
tests/functional/ipset_controller_test.go

After scale-in reserved ips are released back to the pool and if the ipset reconciles for some reason i.e update or infra-operator pod deleted, then the released ip would be assigned to the an exisitng ipset which already has a reservation.
This changes the logic to not try reserve for ipset/network combination which has a reserved ip.
jira: https://issues.redhat.com/browse/OSPRH-19871

Fix ip reassignment for ipset after scale-in

---

controllers/rabbitmq/rabbitmq_controller.go
pkg/rabbitmq/cluster.go
tests/functional/rabbitmq_controller_test.go

The combination of RabbitMQ/Erlang currently in use has issues with TLS1.3, which can cause disconnections/partitions in the rabbitmq cluster during TLS key update.
In order to mitigate this issue until the underlying issue is addressed, force RabbitMQ to use TLS1.2 for connections, in the same way as we did for OSP17 (see [OSPRH-15346](https://issues.redhat.com//browse/OSPRH-15346)).
Jira: https://issues.redhat.com/browse/OSPRH-20331

Force RabbitMQ to stick to TLSv1.2

---

pkg/rabbitmq/cluster.go
tests/functional/rabbitmq_controller_test.go

A follow up to [1] where RabbitMQ was forced to be configured with TLS1.2 to avoid disconnections/partitions in the RabbitMQ cluster during TLS key update.
In addition to [1], the ssl application that is part of the Erlang runtime should also be forced to use TLS1.2, so that other CLI tools like 'rabbitmqctl environment' reports correct TLS1.2 status.
[1] 7cb5eca42954e7fbbe7c575d38c9a76caaf97841
Jira: https://issues.redhat.com/browse/OSPRH-20331

Force Erlang ssl application to stick to TLSv1.2
